### ISSUE TITLE
Silent physical channel close

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse/keyple-service-java-lib#58]
Hello team,
This [PR](https://github.com/eclipse/keyple-service-java-lib/pull/50) introduces a subtle change that does a silent physical channel  and re-open before every selection operation.
This operation can be be very time consuming. For example on a BLUEBIRD device this can take up to 50ms. When trying to select multiple applications on a card, these add up and we end up with a big performance hit.
I don't see much history on the PR so I can't really say for sure but on Keyple V1 this was not the case so I would assume that it should be possible to select multiple applications without closing the physical channel every time in between.
Regards

**Comment by jeanpierrefortune** [comment]
Hello Aghilas,
Thank you for your message about the performance issue and also for digging into the subject and finding the root cause of the problem.
I completely understand how this change can have a negative impact on performance.
We'll be working on it, and will publish a library update soon.
We appreciate your understanding and patience as we work to resolve this issue.
Regards

**Comment by jeanpierrefortune** [comment]
Hello Aghilas,
The fix is available in version [`2.3.1`](https://github.com/eclipse/keyple-service-java-lib/releases/tag/2.3.1).
Regards
